# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 904eb475e79459d61b8b493173473a0f11f49cfc99e0d4e8ce63eb37e0e596f1402b3631b91d47ea86942010601778897696c73cb5940e0473c5aa6551425afd

test:
  secret_key_base: 50745d8d35a5707eae8dfedc3b1f830a80035e24eee674270f76af9db76d3cff38885da9b7340f888fbe33fcacec490390297d7d99693955bae9daca5d71facc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
